name = "LaughPack"
author = "LaughingLeader"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f804f639992d6c9aff4490006d97c062a7052bcf6bb6f0b96c780fd18ed6769"

[versions]
forge = "36.1.65"
minecraft = "1.16.5"
