name = "LaughPack"
author = "LaughingLeader"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee2dbac9618613928f35b01d76f9a117bb52f45f17103425cb6ef14d0ec08279"

[versions]
forge = "36.1.65"
minecraft = "1.16.5"
