name = "Cat Has Wares"
filename = "catwares-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3231/570/catwares-1.0.1.jar"
hash-format = "murmur2"
hash = "1495783887"

[update]
[update.curseforge]
file-id = 3231570
project-id = 451284
release-channel = "beta"
