name = "Catalogue"
filename = "catalogue-1.2.1-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3335/979/catalogue-1.2.1-1.16.5.jar"
hash-format = "murmur2"
hash = "2801934764"

[update]
[update.curseforge]
file-id = 3335979
project-id = 459701
release-channel = "beta"
