name = "Corail Tombstone"
filename = "tombstone-1.16-6.4.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3391/389/tombstone-1.16-6.4.7.jar"
hash-format = "murmur2"
hash = "4105097386"

[update]
[update.curseforge]
file-id = 3391389
project-id = 243707
release-channel = "beta"
