name = "Create Style Vanilla Redstone + Tom's Simple Storage"
filename = "Create Style Vanilla TSS v4.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3395/299/Create Style Vanilla TSS v4.zip"
hash-format = "murmur2"
hash = "2173043552"

[update]
[update.curseforge]
file-id = 3395299
project-id = 492890
release-channel = "beta"
