name = "Dynamic Trees - Biomes O' Plenty"
filename = "DynamicTreesBOP-1.16.5-2.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3394/613/DynamicTreesBOP-1.16.5-2.0.5.jar"
hash-format = "murmur2"
hash = "2045814220"

[update]
[update.curseforge]
file-id = 3394613
project-id = 289529
release-channel = "beta"
