name = "Dynamic Trees"
filename = "DynamicTrees-1.16.5-0.10.0-Beta18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3394/604/DynamicTrees-1.16.5-0.10.0-Beta18.jar"
hash-format = "murmur2"
hash = "1191678918"

[update]
[update.curseforge]
file-id = 3394604
project-id = 252818
release-channel = "beta"
