name = "Ender Mail"
filename = "EnderMail-1.16.5-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3191/672/EnderMail-1.16.5-1.2.0.jar"
hash-format = "murmur2"
hash = "2868162196"

[update]
[update.curseforge]
file-id = 3191672
project-id = 374771
release-channel = "beta"
