name = "Enigmatic Graves"
filename = "EnigmaticGraves-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3388/869/EnigmaticGraves-1.4.2.jar"
hash-format = "murmur2"
hash = "2846872772"

[update]
[update.curseforge]
file-id = 3388869
project-id = 496030
release-channel = "beta"
