name = "FancyMenu [Forge]"
filename = "fancymenu_2.2.0_MC_1.16.2-1.16.5.jar"
side = "client"

[option]
optional = true
description = "FancyMenu is a client-side Minecraft mod to customize ingame menus and the first mod ever with a fully functional ingame menu editor GUI to edit your menu screens without leaving the game! With FancyMenu, you can customize nearly every default-looking menu in the game. Even menus from other mods!"
default = false

[download]
url = "https://edge.forgecdn.net/files/3391/15/fancymenu_2.2.0_MC_1.16.2-1.16.5.jar"
hash-format = "murmur2"
hash = "1720949848"

[update]
[update.curseforge]
file-id = 3391015
project-id = 367706
release-channel = "beta"
