name = "GeckoLib"
filename = "geckolib-forge-1.16.5-3.0.41.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3344/733/geckolib-forge-1.16.5-3.0.41.jar"
hash-format = "murmur2"
hash = "1997604815"

[update]
[update.curseforge]
file-id = 3344733
project-id = 388172
release-channel = "beta"
