name = "Just Enough Items (JEI)"
filename = "jei-1.16.5-7.7.1.110.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3383/214/jei-1.16.5-7.7.1.110.jar"
hash-format = "murmur2"
hash = "1858634730"

[update]
[update.curseforge]
file-id = 3383214
project-id = 238222
release-channel = "beta"
