name = "Lootr"
filename = "lootr-1.16.5-0.0.6.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3392/297/lootr-1.16.5-0.0.6.18.jar"
hash-format = "murmur2"
hash = "3694507173"

[update]
[update.curseforge]
file-id = 3392297
project-id = 361276
release-channel = "beta"
