name = "mGui"
filename = "mgui-1.16.5-3.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3291/267/mgui-1.16.5-3.2.0.jar"
hash-format = "murmur2"
hash = "2047844065"

[update]
[update.curseforge]
file-id = 3291267
project-id = 351914
release-channel = "beta"
