name = "Puzzles Lib"
filename = "PuzzlesLib-v1.0.8-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3394/223/PuzzlesLib-v1.0.8-1.16.5.jar"
hash-format = "murmur2"
hash = "373793753"

[update]
[update.curseforge]
file-id = 3394223
project-id = 495476
release-channel = "beta"
