name = "Refined Storage"
filename = "refinedstorage-1.9.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/933/refinedstorage-1.9.13.jar"
hash-format = "murmur2"
hash = "2727636460"

[update]
[update.curseforge]
file-id = 3351933
project-id = 243076
release-channel = "beta"
