name = "Refined Curios"
filename = "refinedcurios-1.16x-1.153.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/624/refinedcurios-1.16x-1.153.jar"
hash-format = "murmur2"
hash = "652280671"

[update]
[update.curseforge]
file-id = 3358624
project-id = 493113
release-channel = "beta"
