name = "Relics"
filename = "relics-0.2.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3375/134/relics-0.2.3.1.jar"
hash-format = "murmur2"
hash = "2540248023"

[update]
[update.curseforge]
file-id = 3375134
project-id = 445274
release-channel = "beta"
