name = "Small Ships"
filename = "smallships-1.16.5-1.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3381/331/smallships-1.16.5-1.9.0.jar"
hash-format = "murmur2"
hash = "2299235835"

[update]
[update.curseforge]
file-id = 3381331
project-id = 450659
release-channel = "beta"
