name = "Sophisticated Backpacks"
filename = "sophisticatedbackpacks-1.16.4-2.5.0.271.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3338/308/sophisticatedbackpacks-1.16.4-2.5.0.271.jar"
hash-format = "murmur2"
hash = "1670127022"

[update]
[update.curseforge]
file-id = 3338308
project-id = 422301
release-channel = "beta"
