name = "Time Control"
filename = "timecontrol-1.16.5-1.1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/170/timecontrol-1.16.5-1.1.1.0.jar"
hash-format = "murmur2"
hash = "1812175450"

[update]
[update.curseforge]
file-id = 3198170
project-id = 303570
release-channel = "beta"
