name = "Tome of Blood"
filename = "tomeofblood-1.16.5-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3345/873/tomeofblood-1.16.5-1.1.jar"
hash-format = "murmur2"
hash = "4126449405"

[update]
[update.curseforge]
file-id = 3345873
project-id = 438240
release-channel = "beta"
