name = "Waila Harvestability"
filename = "WailaHarvestability-mc1.16.x-forge-1.1.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3289/488/WailaHarvestability-mc1.16.x-forge-1.1.15.jar"
hash-format = "murmur2"
hash = "2924443821"

[update]
[update.curseforge]
file-id = 3289488
project-id = 79287
release-channel = "beta"
